version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "jsonata-portal"
resolve_s3 = true
s3_prefix = "jsonata-portal"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.build]
[default.build.parameters]
use_container = false
