{
  "version": "0.2",
  "default_region": "ap-southeast-1",
  "confirm_changeset": true,
  "resolve_s3": true,
  "resolve_image_repos": true,
  "s3_prefix": "awp-image-workshop",
  "dev": {
    "deploy": {
      "parameters": {
        "stack_name": "awp-image-workshop-dev",
        "capabilities": "CAPABILITY_IAM",
        "parameter_overrides": "Environment=dev StageName=v1"
      }
    }
  },
  "staging": {
    "deploy": {
      "parameters": {
        "stack_name": "awp-image-workshop-staging",
        "capabilities": "CAPABILITY_IAM",
        "parameter_overrides": "Environment=staging StageName=v1"
      }
    }
  },
  "prod": {
    "deploy": {
      "parameters": {
        "stack_name": "awp-image-workshop-prod",
        "capabilities": "CAPABILITY_IAM",
        "parameter_overrides": "Environment=prod StageName=v1"
      }
    }
  }
}
