# SAM CLI Configuration
# More info: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default.deploy.parameters]
stack_name = "awp-examples"
resolve_s3 = true
s3_prefix = "awp-examples"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
