# CASFA (CAS For Agents) - SAM CLI Configuration
#
# IMPORTANT: Do NOT put secrets in this file!
# IdP credentials (GOOGLE_CLIENT_SECRET, MICROSOFT_CLIENT_SECRET) should be in .env
# The deploy script will read from .env and pass them to SAM.
#
version = 0.1

[default.deploy.parameters]
stack_name = "casfa"
resolve_s3 = true
s3_prefix = "casfa"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
# Non-sensitive parameters only - secrets are injected by deploy script from .env
parameter_overrides = "CallbackBaseUrl=\"https://casfa.awp.shazhou.me\" CustomDomainName=\"casfa.awp.shazhou.me\" CustomDomainCertificateArn=\"arn:aws:acm:us-east-1:914369185440:certificate/96bc8821-749b-4f10-921d-a29787ab6fbc\" CognitoDomain=\"casfa-ui\""
